
name: Release Please Test
on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Deployment environment'
                # required: true
                default: DEV
                type: choice
                options:
                - DEV
                - QA
permissions:
    contents: write
    pull-requests: write

jobs:
    release-please:
      runs-on: ubuntu-latest
      steps:
        - uses: googleapis/release-please-action@v4
          with:
            release-type: node